@host = http://localhost:3000
@eventId = {{CreateEvent.response.body.data.id}}
@date = {{$datetime "DD/MM/YYYY" 365}}



### Health Check
# @name HealthCheck
GET {{host}}/health HTTP/1.1

### Create New Event
# @name CreateEvent
POST {{host}}/api/events HTTP/1.1
Content-Type: application/json

{
  "name": "Charity Auction",
  "date": "21/12/2025",
  "capacity": 100,
  "costPerTicket": 5
}

### Get Event
# @name GetEvent
GET {{host}}/api/events/{{eventId}} HTTP/1.1
Content-Type: application/json


### Purchase Tickets
# @name PurchaseTickets
POST {{host}}/api/events/purchase HTTP/1.1
Content-Type: application/json

{
  "eventId": "{{eventId}}",
  "nTickets": 1
}
